server:
  port: 8185

spring:
  jpa:
    open-in-view: false # comes as true by default which will keep the DB connection open for a long time
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource: # binaryTransfer=true will increase the performance as it transfers the data in binary, and reWriteBatchedInserts=true will increase data insertion performance as it will insert multiple data in a single statement, and stringtype=unspecified will prevent type checking for UUIDs.
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: 1777
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always # will run the init schema file always when starting the application.
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql